### ISSUE TITLE
The openshift download versions have changed

### ISSUE THREAD

**Issue by jgnoonan** [ibm-cloud-architecture/refarch-privatecloud#29] opened 2019-12-20 20:03 UTC
Version has changed from 4.2.0 to 4.2.10.  The wget commands need to be updated to reflect that.

**Comment by VictorHavard** [comment] 2020-02-10 00:26
Duplicate of https://github.com/ibm-cloud-architecture/refarch-privatecloud/issues/32 which has been resolved.

**Closed as completed by VictorHavard** 2020-02-10 00:26 UTC
Labels: duplicate
