### ISSUE TITLE
Can't get the Configure Client information

### ISSUE THREAD

**Issue by patrocinio** [ibm-cloud-architecture/refarch-privatecloud#2] opened 2017-06-16 14:16 UTC
logged in using Eduardo’s id. trying to configure the client. from Account/Configure client, I got a blank windows, instead of the kubctl commands. do you see the same?

**Comment by VictorHavard** [comment] 2017-06-30 16:10
I believe this can be resolved by clearing the browser's cache and trying it again.  I cannot reproduce the error myself in order to attempt the resolution.

**Closed as completed by VictorHavard** 2017-06-30 16:10 UTC
